#!/bin/sh

cd ~
if [ ! -e '~/.cache/dein' ]; then
  mkdir -p ~/.cache/dein
fi
curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh
sh ./installer.sh ~/.cache/dein
rm ./installer.sh

for rc in gemrc gitconfig screenrc tmux.conf tmux-powerlinerc zshrc vimrc
do
  rm -f ~/.$rc && ln -s ~/dotfiles/$rc ~/.$rc
done

rm -f ~/.vimshrc && ln -s ~/dotfiles/zshrc.alias ~/.vimshrc

rm -rf ~/dotfiles/tmux/tmux-powerline
git clone git@github.com:erikw/tmux-powerline.git ~/dotfiles/tmux/tmux-powerline
ln -s ~/dotfiles/tmux/my-tmux-powerline/themes/mytheme.sh ~/dotfiles/tmux/tmux-powerline/themes/mytheme.sh

if [ -e '/etc/redhat-release' ]; then
  rpm -q patch || sudo yum -y install patch
fi
patch -u ~/dotfiles/tmux/tmux-powerline/segments/vcs_branch.sh < ~/dotfiles/tmux/my-tmux-powerline/segments/vcs_branch.patch
