#!/bin/sh

if [ ! -e "$HOME/dotfiles/vim/bundle/" ]; then
  mkdir -p ~/dotfiles/vim/bundle
  git clone git@github.com:Shougo/neobundle.vim.git ~/dotfiles/vim/bundle/neobundle.vim
fi

for rc in gemrc gitconfig screenrc tmux.conf tmux-powerlinerc zshrc vim vimrc
do
  rm -f ~/.$rc && ln -s ~/dotfiles/$rc ~/.$rc
done

rm -f ~/.vimshrc && ln -s ~/dotfiles/zshrc.alias ~/.vimshrc

rm -rf ~/dotfiles/tmux/tmux-powerline
git clone git@github.com:erikw/tmux-powerline.git ~/dotfiles/tmux/tmux-powerline
ln -s ~/dotfiles/tmux/my-tmux-powerline/themes/mytheme.sh ~/dotfiles/tmux/tmux-powerline/themes/mytheme.sh

if [ -e '/etc/redhat-release' ]; then
  rpm -q patch || sudo yum -y install patch
fi
patch -u ~/dotfiles/tmux/tmux-powerline/segments/vcs_branch.sh < ~/dotfiles/tmux/my-tmux-powerline/segments/vcs_branch.patch
